---
title: "Class18: Cancer Genomics"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## NCI Genomic Data Commons

Lets talk to the NCI

```{r}
library(GenomicDataCommons)
library(TCGAbiolinks)
library(maftools)
```

```{r}
status()
```

```{r}
cases_by_project <- cases() %>%
  facet("project.project_id") %>%
  aggregations()
head(cases_by_project)
```

```{r}
x <- cases_by_project$project.project_id

# Plot with 'log' for y axis and rotate labels with 'las'
#par(___)  
barplot(x$doc_count, names.arg=x$key, log="y",las=2)
```

```{r}
maf.file <- GDCquery_Maf(tumor="PAAD", pipelines = "mutect")
```

```{r}
head(maf.file)
```

```{r}
vars = read.maf(maf = maf.file, verbose = FALSE)
```


```{r}
lollipopPlot(vars, gene='TP53')
```

```{r}
library(bio3d)
seqs <- read.fasta("~/Downloads/lecture18_sequences.fa")
seqs
```

```{r}
seqs <- seqaln(seqs)
```

```{r}
library(bio3d)
x<- read.fasta("bimm143midtermproject.fasta")
```

```{r}
matrix<- seqidentity(x)
```

```{r}
plot<- heatmap(matrix)
```

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  




